- src/formpack/schema/fields.py
> Choicename hotfix

- .travis.yml
- src/formpack/utils/expand_content.py
- src/formpack/utils/flatten_content.py
- tests/test_autoreport.py
- tests/test_expand_content.py
`media::image` was getting flattened to `media::image::None`.
this is fixed and tested
> properly expands/flattens translated content

- requirements.txt
until they fix https://github.com/kz26/PyExcelerate/issues/52
> Pin PyExcelerate to version 0.6.7

- .travis.yml
> Coveralls Fix

- README.rst
I really can't figure out how to get them on the same line...
> Add Coveralls badge.

- .travis.yml
- setup.py
- src/formpack/pack.py
- src/formpack/utils/array_to_xpath.py
- src/formpack/utils/expand_content.py
- src/formpack/utils/flatten_content.py
- src/formpack/utils/replace_aliases.py
- src/formpack/utils/xform_tools.py
- src/formpack/version.py
- tests/test_array_to_xpath.py
- tests/test_expand_content.py
- tests/test_formpack_internals.py
- tests/test_replace_aliases.py
- tests/test_utils.py
* Avoid confusion with json-schema, where `$` has a different meaning.
* Also: changed `flatten_content` , `expand_content`, and `replace_aliases` to copy the content by default
> version 1.2

- tests/fixtures/site_inspection/__init__.py
- tests/fixtures/site_inspection/v1.json
- tests/fixtures/site_inspection/v2.json
- tests/fixtures/site_inspection/v3.json
- tests/fixtures/site_inspection/v4.json
- tests/fixtures/site_inspection/v5.json
- tests/test_autoreport.py
- tests/test_exports.py
- tests/test_fixtures_valid.py
New passing tests:
* TestAutoReport.test_list_fields_from_many_versions_on_packs
* TestFormPackFixtures.test_site_inspection
New failing tests:
* TestAutoReport.test_simple_multi_version_report
* TestFormPackExport.test_headers_of_multi_version_exports
> New 'site_inspection' fixture and associated tests

- src/formpack/reporting/export.py
- tests/fixtures/restaurant_profile/v1.json
- tests/fixtures/restaurant_profile/v2.json
- tests/fixtures/restaurant_profile/v3.json
- tests/fixtures/restaurant_profile/v4.json
- tests/test_exports.py
Add `_uuid` to `restaurant_profile` fixture for testing
> Include `copy_fields` for all versions; fixes #132

- src/formpack/reporting/export.py
- tests/fixtures/nested_grouped_repeatable/__init__.py
- tests/fixtures/nested_grouped_repeatable/v1.json
- tests/test_exports.py
> Extend chunk lists instead of overwriting them

- src/formpack/schema/datadef.py
- src/formpack/schema/fields.py
- src/formpack/version.py
- tests/fixtures/grouped_translated/__init__.py
- tests/fixtures/grouped_translated/v1.json
- tests/test_expand_content.py
- tests/test_exports.py
> Fix translated hierarchical labels

- src/formpack/schema/datadef.py
- src/formpack/schema/fields.py
- tests/test_exports.py
>  Use XML names when labels/translations missing 

- src/formpack/pack.py
- src/formpack/version.py
- tests/fixtures/restaurant_profile/__init__.py
- tests/test_exports.py
- tests/test_formpack_internals.py
Fixes #149; fixes #150. Still to resolve: https://github.com/kobotoolbox/formpack/issues/151
> Fix issues related to changing a question's definition without changing its name

- src/formpack/constants.py
- src/formpack/pack.py
- src/formpack/reporting/export.py
- src/formpack/utils/expand_content.py
- src/formpack/utils/flatten_content.py
- src/formpack/utils/spreadsheet_content.py
- tests/test_expand_content.py
- tests/test_exports.py
- tests/test_utils_flatten_content.py
Closes #153 by setting the separator for 'hxl' to ''
> Allow each tag column to have its own separator

- src/formpack/utils/expand_content.py
- tests/test_expand_content.py
See http://hxlstandard.org/standard/1_1beta/tagging/#grammar
> Allow underscores in HXL grammar; fixes #160

- src/formpack/pack.py
- tests/fixtures/build_fixture.py
- tests/fixtures/site_inspection/__init__.py
- tests/fixtures/site_inspection/v6.json
- tests/test_exports.py
- tests/test_formpack_internals.py
> Columns in exports are out of sequence: Fix. New Algorithm

- src/formpack/schema/fields.py
- tests/test_formpack_internals.py
It fixes the error reported [here](https://github.com/kobotoolbox/kpi/issues/1624). 
It still needs a unittest though.
> Unlabelled choices and questions with translations - fix

- src/formpack/utils/array_to_xpath.py
- tests/test_array_to_xpath.py
* "@if": if(test, thenval, elseval)
* "@comma_parens": ['x', 'y', 'z'] -> "(x, y, z)"
* "@case": avoid deeply nested
"if(test, thenval, if(test2, ...))"
> added a few new json xpath functions with tests

- requirements.txt
- src/formpack/reporting/export.py
Allows successful export of dataset that failed with
`SerialisationError: unknown error` under Openpyxl and
`LargeZipFile: Filesize would require ZIP64 extensions` under PyExcelerate
> Replace Openpyxl with XlsxWriter; closes #171

- src/formpack/reporting/export.py
Per https://github.com/kobotoolbox/formpack/pull/172#discussion_r187436107
> Rename nested function parameter

- dev-requirements.txt
- setup.py
- src/formpack/reporting/export.py
- src/formpack/utils/exceptions.py
- src/formpack/utils/geojson.py
- tests/fixtures/all_geo_types/__init__.py
- tests/fixtures/all_geo_types/v1.json
- tests/fixtures/all_geo_types/v2.json
- tests/fixtures/build_fixture.py
- tests/test_exports.py
This has been rebased on top of #202.
Closes #200.
> Add GeoJSON export feature

- src/formpack/reporting/export.py
- tests/test_exports.py
> Include HXL tag only once for select_multiples

- .coveragerc
- .github/workflows/pytest-with-coveralls.yml
- dev-requirements-py3.txt
- dev-requirements.txt
Drumroll... will reported coverage exceed 0%?
> Upgrade coverage and fix paths

- src/formpack/version.py
- tests/fixtures/or_other/v1.json
> Fix label handling for `or_other` with translations

- src/formpack/pack.py
- tests/test_formpack_internals.py
This is a redo of #276 on top of #286, the squashed redo of #270.
> Fix combining fields for repeat groups across versions

- src/formpack/schema/fields.py
- tests/fixtures/nested_grouped_repeatable/__init__.py
- tests/fixtures/nested_grouped_repeatable/v1.json
- tests/fixtures/nested_grouped_repeatable/v2.json
- tests/test_exports.py
This is a redo of #274 on top of #286, the squashed redo of #270.
> Handle `inf` and `nan` values for XLS exports

- src/formpack/constants.py
- src/formpack/utils/expand_content.py
- tests/test_expand_content.py
This is a redo of #280 on top of #286, the squashed redo of #270.
>  Fix handling of translated media

- src/formpack/reporting/export.py
- tests/fixtures/simple_nested_grouped_repeatable/__init__.py
- tests/fixtures/simple_nested_grouped_repeatable/v1.json
- tests/fixtures/simple_nested_grouped_repeatable/v2.json
- tests/test_expand_content.py
- tests/test_exports.py
This is a redo of #281 on top of #286, the squashed redo of #270.
> Fix for nested repeats without fields in their section

- setup.py
> Pin pyxform to `1.7.0`

- pyproject.toml
- src/formpack/reporting/export.py
- src/formpack/utils/exceptions.py
- tests/fixtures/quotes_newlines_and_long_urls/__init__.py
- tests/test_exports.py
> Handle Excel limits: URLs, cell content, and worksheet boundaries

- src/formpack/constants.py
- src/formpack/reporting/export.py
- src/formpack/schema/fields.py
- src/formpack/utils/string.py
- src/formpack/version.py
- tests/fixtures/analysis_form/analysis_form.json
- tests/fixtures/analysis_form/v1.json
- tests/fixtures/analysis_form/v2.json
- tests/fixtures/analysis_form_advanced/analysis_form.json
- tests/fixtures/analysis_form_advanced/v1.json
- tests/test_additional_field_exports.py
- tests/test_fixtures_valid.py
Please refer to the comments I've left directly on the diff
Closes kobotoolbox/kpi#4621
Closes kobotoolbox/kpi#4622
Closes kobotoolbox/kpi#4623
> Add support for qualitative analysis questions
