kobotoolbox/formpack

src/formpack/pack.py
src/formpack/utils/array_to_xpath.py
src/formpack/utils/expand_content.py
src/formpack/utils/flatten_content.py
tests/test_array_to_xpath.py
tests/test_expand_content.py
tests/test_utils.py

* The expanded form will be easier to handle translations, xpaths consistently in the UI. (No more string parsing of column names)
* The flattened format can export directly to XLS and be a valid xlsform

Utils for 'expanding' and 'flattening' xlsform json

---

requirements.txt
src/formpack/constants.py
src/formpack/pack.py
src/formpack/reporting/autoreport.py
src/formpack/reporting/export.py
src/formpack/schema/datadef.py
src/formpack/schema/fields.py
src/formpack/utils/array_to_xpath.py
src/formpack/utils/expand_content.py
src/formpack/utils/flatten_content.py
src/formpack/utils/replace_aliases.py
src/formpack/version.py
tests/test_autoreport.py
tests/test_expand_content.py
tests/test_exports.py
tests/test_fixtures_valid.py
tests/test_submissions.py
tests/test_utils.py

This means the core formpack code will not need to do any parsing of aliases or regex parsing of strings in the XLSForm cells.
Includes a merge of the `"aliases"` branch as well.

Allow formpack to work on the content that has been expanded

---

src/formpack/errors.py
src/formpack/schema/datadef.py
src/formpack/utils/__init__.py
src/formpack/utils/flatten_content.py
src/formpack/utils/replace_aliases.py
src/formpack/utils/xform_tools.py
src/formpack/version.py
tests/fixtures/restaurant_profile/v3.json
tests/test_fixtures_valid.py
tests/test_formpack_internals.py
tests/test_replace_aliases.py
tests/test_submissions.py

* doesn't incidentally remove `id_string` setting
* no longer dependent on a specific version of pyxform

Fixing some issues with aliases

---

src/formpack/pack.py
tests/test_formpack_internals.py

This allows to disable title ellipsizing, useful when displaying form preview in KoBoToolbox. (This comes with a corresponding kpi pull request to actually use that)

Add ellipsize_title parameter to formpack constructor

---

src/formpack/constants.py
src/formpack/pack.py
src/formpack/reporting/export.py
src/formpack/utils/__init__.py
src/formpack/utils/string.py
tests/fixtures/long_names/__init__.py
tests/fixtures/long_names/v1.json
tests/test_exports.py
tests/test_formpack_internals.py

Fixes #122. Moves code pertaining to this limitation out of the formpack core
and places it exclusively within the Excel export logic.
Once this is merged, we will need to update [the pinned formpack commit in KPI's requirements](https://github.com/kobotoolbox/kpi/blob/dbf0a09be819f915a788c31924f89c392b890f52/requirements/requirements.txt#L8) and remove [the reference to `ellipsize_title`](https://github.com/kobotoolbox/kpi/blob/dbf0a09be819f915a788c31924f89c392b890f52/kpi/models/asset.py#L762) from the `AssetSnapshot` code.

Keep all Excel sheet names under 31 characters.

---

src/formpack/pack.py
src/formpack/reporting/export.py
tests/test_exports.py
tests/test_formpack_internals.py

...and enable previously failing unit test. Fixes #99‽
Built on top of https://github.com/kobotoolbox/formpack/pull/128.

Refactor exports to use `get_fields_for_versions`

---

src/formpack/pack.py
src/formpack/reporting/export.py
src/formpack/schema/fields.py
src/formpack/utils/expand_content.py
src/formpack/utils/flatten_content.py
src/formpack/utils/spreadsheet_content.py
tests/fixtures/dietary_needs/v1.json
tests/fixtures/hxl_grouped_repeatable/__init__.py
tests/fixtures/hxl_grouped_repeatable/v1.json
tests/test_expand_content.py
tests/test_exports.py
tests/test_utils_flatten_content.py

as secondary header rows. Includes @dorey's work to support expanding and flattening `hxl` columns in XLSForms. Closes #134

Support exporting tag column values

---

src/formpack/pack.py
src/formpack/schema/fields.py
tests/fixtures/literacy_test/__init__.py
tests/fixtures/literacy_test/v1.json
tests/test_exports.py

Support exporting data collected with https://github.com/kobotoolbox/enketo-literacy-test-widget, which uses a modified `select_multiple` question (with `appearance` set to `literacy`) that prepends special, non-choice parameters to the value.

Add new literacy test field type

---

dev-requirements.txt
requirements.txt
setup.py
src/formpack/constants.py
src/formpack/reporting/export.py
src/formpack/utils/string.py
tests/test_exports.py

and tame dependencies in general (updates, conflict resolution). Running `python setup.py develop` now actually installs what's in `dev-requirements.txt`.
Fixes #155.

Use Openpyxl for exports instead of PyExcelerate

---

src/formpack/schema/fields.py
tests/fixtures/auto_report_extended_fields/__init__.py
tests/fixtures/auto_report_extended_fields/v1.json
tests/test_autoreport.py

This error occurred when stats were disaggregated in more than 5 items. 
We don't return more than 5 items, all others are grouped and displayed under an `ellipsis` label.
But data was grouped only in the `frequency` list, not the `percentage` one.
I have also added a simple test which validates that both lists have the same length when stats are disaggregated with more than 5 items.

Fixed missing item in percentage list when stats are disaggregated

---

src/formpack/pack.py
src/formpack/reporting/export.py
src/formpack/schema/fields.py
tests/fixtures/favorite_coffee/__init__.py
tests/fixtures/favorite_coffee/v1.json
tests/fixtures/favorite_coffee/v2.json
tests/test_exports.py

Exporting data with multiple response options previously deleted shifts values - fix

---

.travis.yml
dev-requirements.txt
src/formpack/reporting/export.py
tests/fixtures/quotes_newlines_and_long_urls/__init__.py
tests/test_exports.py

Fixes #193. The long URL in the new test fixture is for the next bug that needs to be fixed :wink:

Escape `quote` during CSV exports by doubling it

---

src/formpack/pack.py
src/formpack/reporting/autoreport.py
src/formpack/schema/fields.py
tests/test_autoreport.py

autoreport ignores non-numeric values in numeric field

---

src/formpack/utils/flatten_content.py

Reverts kobotoolbox/formpack#180, which isn't needed now that XLSForm/pyxform#237 has been merged.

Revert "Work around XLSForm/pyxform#236 by converting"

---

.travis.yml
README.rst
dev-requirements.txt
requirements.txt
setup.py

* Use abstract dependencies in `setup.py`;
* Remove `requirements.txt`;
* Use `-e .` in dev-requirements.txt;
* Instruct developers to use `pip install` instead of `setup.py develop`.

Improve packaging and update dev. instructions:

---

src/formpack/utils/future.py
src/formpack/utils/xls_to_ss_structure.py

`unichr` doesn't exist in Python3. 
Allow `unichr` usage with Python 2 and Python 3.
To be removed when Python 2 support is dropped.

Added Python 3 support for "unichr"

---

src/formpack/schema/fields.py

Related to https://github.com/kobotoolbox/kpi/issues/2510

Removed useless return super().__init()

---

src/formpack/version.py
tests/test_formpack_internals.py

* pyxform has an undocumented way to ignore questions from surveys (`disabled=TRUE`)
* surveys were being deployed in KPI which had questions with this attribute
* exports were breaking because formpack was looking for choice lists that didn't exist because the questions were "commented out"
fixes #219

ignore questions specified to be ignored

---

src/formpack/schema/fields.py
src/formpack/utils/__init__.py
src/formpack/utils/statistics.py

Python 3.8 changed the behavior of `mode()` to return the first mode if
no unique mode exists: https://bugs.python.org/issue35892#msg336570.
This returns to the old behavior where an exception is raised if there's
no unique mode

Add utility function that returns a single mode

---

src/formpack/utils/flatten_content.py
tests/test_formpack_internals.py

Goal: make formpack-to-XML conversion behave the same way as
formpack-to-XLSForm-to-XML conversion. The better those match, the
better KPI's previews will match its deployed forms.
In this particular case, pyxform discarded empty cells when loading from
XLSForm, but formpack was preserving empty strings when sending Python
structures to pyxform for conversion to XML. One consequence of this was
empty translated labels being shown for groups in KPI previews, i.e.
kobotoolbox/kpi#2707.

Omit empty group labels when generating XML

---

src/formpack/reporting/export.py

Joining tags into comma-separated lists now handles the `_submission_` prefix and all list objects are coerced to strings before attempting to export to xls format.
closes #232

Fix broken xls exports

---

src/formpack/reporting/export.py
src/formpack/schema/datadef.py
src/formpack/schema/fields.py
src/formpack/utils/ordered_collection.py
tests/test_exports.py

Previously setting `multiple_select` to `summary` or `details` only affected the headers of exports; all the data rows always behaved as if it were set to `both`. This change fixes #234.
* Since formpack receives `multiple_select` only from the `Export()` constructor, set it as an instance attribute instead of passing it to various internal methods as an argument.
* Stop attempting to set up export-specific data structures in field class constructors, since fields are initialized before export options are known.
* NB: This removes the `FormDataDef.value_names` and `FormField.empty_result` optimizations. I haven't noticed a performance decrease (yet).
* Delegate the handling of missing values to the `format()` method of field classes by passing `None` as the value.
* Most fields return an …

Fix `multiple_select` export option

---

src/formpack/schema/fields.py
tests/fixtures/select_one_from_previous_answers/__init__.py
tests/fixtures/select_one_from_previous_answers/v1.json
tests/test_exports.py

Handle the case of `select_one ${question_name}` to support XLSForm/pyxform#472.
closes #248

Support choice from previous repeat answers for `select_one`

---

src/formpack/schema/fields.py
tests/test_exports.py

…so that columns remain consistent for existing workflows. This temporarily undoes the work in #258.
Internal discussion: https://chat.kobotoolbox.org/#narrow/stream/4-KoBo-Dev/topic/links.20.2F.20URL.20to.20attachments.20in.20table

Temporarily disable new media URL columns

---

src/formpack/version.py
tests/fixtures/translations_labels_mismatch/__init__.py
tests/fixtures/translations_labels_mismatch/v1.json
tests/test_exports.py

This is a redo of #284 on top of #286, the squashed redo of #270.

Fix translations and labels mismatch error message

---

dev-requirements.txt
tests/test_kobo_locking.py

`xlwt` is no longer required, replaced by `openpyxl`.

Remove `xlwt` requirement

---

src/formpack/utils/replace_aliases.py

removed simserial and subscriberid from the meta data as Google no longer provides this information

Remove simserial and subscriberid from metadata

---

src/formpack/utils/expand_content.py
tests/test_expand_content.py

Handle multiple spaces in select type questions between `list_name` and `or_other` option.
closes #303

Handle multiple spaces in or_other

---

src/formpack/pack.py
src/formpack/utils/xlsform_parameters.py
src/formpack/version.py
tests/test_default_image_max_pixels.py

This would go with a (yet to be created) KPI pull request to avoid deploying surveys collecting giant photos (Android default camera app photo sizes vary quite a bit, but generally larger than needed).
Closes issue #312

Allow a default value to be set for max-pixels on questions of type: "image"

---

src/formpack/utils/expand_content.py
tests/test_expand_content.py

select_multiple_from_file to reference
a file, rather than a remote list ID

expand select_*_from_file

---

pyproject.toml
src/formpack/utils/flatten_content.py
tests/test_utils_flatten_content.py

…to `select_one_from_file file.csv` instead of having `select_one_from_file` in the `type` column and `file.csv` in a nonstandard `file` column.
Fixes a problem introduced in https://github.com/kobotoolbox/formpack/pull/314
Reminder: update `formbuilder-misc` branch in KPI to require the new formpack commit hash once this is merged

Properly flatten select_one_from_file

---

src/formpack/utils/flatten_content.py
tests/test_utils_flatten_content.py

…to `select_multiple_from_file file.csv` instead of having `select_multiple_from_file` in the `type` column and `file.csv` in a nonstandard `file` column.
Fixes a problem introduced in #314, mistakenly left unaddressed in #318

Properly flatten select_multiple_from_file

---

src/formpack/utils/expand_content.py
tests/test_exports.py

* `DeprecationWarning: invalid escape sequence '\s'`
* `DeprecationWarning: isfile is deprecated; use is_file`

Fix deprecation warnings

---

src/formpack/constants.py
src/formpack/utils/bugfix.py
src/formpack/utils/expand_content.py
tests/test_bugfix.py
tests/test_exports.py

Correct the mistake in #321 that merged two constants both named `MEDIA_TYPES` together. In reality, one constant was used for *media column names*, and the other for question types that collect attachments. The former is now renamed to `MEDIA_COLUMN_NAMES`.
The utility function `formpack.utils.bugfix.repair_file_column_content_in_place()` is also provided to repair content that was damaged by this mistake.
Fixes #322. For more details, please read the description of that issue.

Fix `Mismatched labels and translations` error for forms using multiple languages and `select_one_from_file` or `select_multiple_from_file`

---

src/formpack/utils/string.py
tests/test_utils_string.py

Fixes "export failed" when trying to export forms whose name starts or ends with an apostrophe
Make xls worksheet names more Excel-compatible, by replacing leading or trailing apostrophes with underscores.
Add tests for similar modifications we already do:
- [replacing other forbidden characters](https://github.com/kobotoolbox/formpack/commit/a19c9396b7c270c191df903894df0cdacd3bd643)
- [keep the sheet name length <= 31 characters](https://github.com/kobotoolbox/formpack/commit/667657aebd6cd4c9be10d3b2a24832a6e81c51c6)
Fixes an export failing in kpi. 
Internal discussion:  ["Apostrophe at the end of the title breaks data downloading."]( https://chat.kobotoolbox.org/#narrow/stream/6-Kobo-Support/topic/Apostrophe.20at.20the.20end.20of.20the.20title.20breaks.20data.20downloading)

fix: swap '_' for leading or trailing apostrophes in worksheet names

---

src/formpack/schema/fields.py

Refer to https://github.com/kobotoolbox/kpi/pull/5238 for information about how to test `background-geopoint`.
Prior to this PR, `background-geopoint` questions are exported as if they were text; now, they're exported as GPS fields that are split across multiple columns for `_latitude`, `_longitude`, `_altitude`, and `_precision`.
I'm happy that the fallback behavior was exporting as text instead of crashing :)

feat: export `background-geopoint` as GPS field

---

setup.py
tests/test_exports.py

To verify, follow the README to set up a virtual environment and run pytest. All tests should pass. The removed library was used only by unit tests.
Attention: if you receive `AttributeError: 'Survey' object has no attribute 'update'`, this is caused by breaking changes in pyxform 3.0.0. Run `pip install pyxform==2.2.0` and try again.
Internal discussion: https://chat.kobotoolbox.org/#narrow/stream/4-Kobo-Dev/topic/path.2C.20pathlib.2C.20path.2Epy

Replace path.py with 2-line helper function

---

dev-requirements.txt

Because this is a library, dependencies (in setup.py) are unpinned, but development dependencies (for running pytest, etc.) *are* pinned. This updates those pinned dependencies to match what happens when this library is installed as a dependency of kpi.
To verify, follow the README to set up a virtual environment and run pytest. All tests should pass.
Attention: if you receive `AttributeError: 'Survey' object has no attribute 'update'`, this is caused by breaking changes in pyxform 3.0.0. Run `pip install pyxform==2.2.0` and try again.

Update development dependencies to match kobotoolbox/kpi

---

.github/workflows/pytest-with-coveralls.yml
dev-requirements.txt
src/formpack/schema/fields.py
src/formpack/version.py
tests/fixtures/analysis_form/analysis_form.json
tests/fixtures/analysis_form/v1.json
tests/fixtures/analysis_form/v2.json
tests/fixtures/analysis_form_advanced/analysis_form.json
tests/fixtures/analysis_form_advanced/v1.json

Removed deprecated qpath usage in export logic and fixed missing supplement details columns when forms include (nested) groups.

fix: remove usage of obsolete "qpath" to restore supplement details columns with (nested) groups

---

src/formpack/schema/fields.py
tests/fixtures/media_types/v1.json
tests/test_exports.py

Set `{field}_URL` to 'Deleted' for deleted attachments, when `include_media_url` is True.
- Updated the logic to set `{field}_URL` to 'Deleted' if the attachment is marked as deleted and `include_media_url` is True.
- Updated the test fixture to include submissions with deleted attachments and extended unit tests to verify the correct behavior of `{field}_URL` field.

feat: Set `{field}_URL` to `Deleted` for attachments marked as deleted
